/*******************************************************************************
** texture.h (opengl texture management)
*******************************************************************************/

#ifndef TEXTURE_H
#define TEXTURE_H

/*#include <SDL2/SDL_opengl.h>*/
#include <glad/glad.h>

#define TEXTURE_ALPHA_COLOR_MASK        0x3F
#define TEXTURE_FLAG_HAS_ALPHA_CHANNEL  0x40
#define TEXTURE_FLAG_SIZE_256_X_256     0x80

enum
{
  TEXTURE_INDEX_DOUBLE_SNAKE_FAERIE_VENUSIAN = 0,
  TEXTURE_INDEX_ENVIRONMENT_SYMBOLS_SUBMERGED,
  TEXTURE_INDEX_FONT,
  TEXTURE_INDEX_HUD_PICKUPS,
  TEXTURE_INDEX_IMP_JIANGSHI,
  TEXTURE_INDEX_MUMMY_POLTERGEIST_LASER_GUNS,
  TEXTURE_INDEX_OBSTACLES_SPELLS,
  TEXTURE_INDEX_PLAYER_GHOST_PUMPKIN_MASK,
  TEXTURE_INDEX_PUSHABLE_OBJECTS,
  TEXTURE_INDEX_REVERSE_DOUBLE_LIL_BOT_WISP_FROG,
  TEXTURE_INDEX_SWITCHES,
  TEXTURE_INDEX_THEME_ALCHEMY,
  TEXTURE_INDEX_THEME_APOGEE,
  TEXTURE_INDEX_THEME_ARENA,
  TEXTURE_INDEX_THEME_ARMORY,
  TEXTURE_INDEX_THEME_BALLROOM,
  TEXTURE_INDEX_THEME_CRYPT,
  TEXTURE_INDEX_THEME_DESSERTS,
  TEXTURE_INDEX_THEME_DUNGEON,
  TEXTURE_INDEX_THEME_FOYER,
  TEXTURE_INDEX_THEME_FUTURE,
  TEXTURE_INDEX_THEME_GARDENS,
  TEXTURE_INDEX_THEME_GOLDEN,
  TEXTURE_INDEX_THEME_HEAVEN,
  TEXTURE_INDEX_THEME_LABYRINTH,
  TEXTURE_INDEX_THEME_LIBRARY,
  TEXTURE_INDEX_THEME_PAGAN,
  TEXTURE_INDEX_THEME_PENTOMINO,
  TEXTURE_INDEX_THEME_PERISTYLE,
  TEXTURE_INDEX_THEME_SHRINE,
  TEXTURE_INDEX_THEME_TIBET,
  TEXTURE_INDEX_THEME_WATERS,
  TEXTURE_INDEX_THEME_YGGDRASIL,
  TEXTURE_INDEX_TRAPS,
  TEXTURE_INDEX_UNDINE_SORCERESS_WITCH_GUARDIAN,
  TEXTURE_NUM_INDICES
};

extern GLuint* G_texture_ids;

/* function declarations */
short int textures_init();
short int textures_deinit();
short int texture_load_all_from_file(char* filename);

#endif
